name: Publish VS Code Extension

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the main branch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Use Node.js version 18

    - name: Install dependencies
      run: npm install

    - name: Run Compile
      run: npm run compile

    - name: Package Extension with npx
      run: npx vsce package

    - name: Publish Extension with npx
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}  # Use a secret for your Personal Access Token
      run: npx vsce publish
